version: "3"

tasks:
  html:
    desc: build html
    cmds:
      - find ./ -name '*.adoc' -exec asciidoctor {} +

  cv-pdf:
    desc: build cv pdf
    cmds:
      - asciidoctor-pdf cv/index.adoc
      - mv cv/index.pdf cv/boris-somodvarac.pdf

  lfs:
    desc: install git lfs
    cmds:
      - yay -S git-lfs
      - git lfs install
      - git lfs track "*.pdf"
      - git add .gitattribute

  venv:
    desc: create venv
    cmds:
      - python -mvenv .venv

  reqs:
    desc: install requirements
    cmds:
      - .venv/bin/pip install -r requirements.txt

  push:
    desc: git push for all remotes
    cmds:
      - git push origin
      - git push github
